### ISSUE TITLE
Hev-display segmentation fault

### ISSUE THREAD

**Issue by chrisburr** [hev-sw/hev-sw#27]
Last night when I left `hev-display --opengl` running on my 3B+ with data coming from `python3 hevserver.py --inputFile share/sample.txt` `hev-display` crashed with `Segmentation fault` after a little more than 6 hours.

```
Unable to query physical screen size, defaulting to 100 dpi.
To override, set QT_QPA_EGLFS_PHYSICAL_WIDTH and QT_QPA_EGLFS_PHYSICAL_HEIGHT (in millimeters).
fakeAlarm:  "Oxygen supply fail"
fakeAlarm:  "Battery low"
fakeAlarm:  "Intentional stop"
fakeAlarm:  "High VTE"
fakeAlarm:  "Low PEEP"
Socket is disconnected, trying to reconnect
ERROR: Got invalid document
"}"
ERROR: Got invalid document
"ype\": \"broadcast\", \"sensors\": {\"version\": 161, \"timestamp\": 3318.700000000002, \"fsm_state\": \"IDLE\", \"pressure_air_supply\": 0, \"pressure_air_regulated\": 0, \"pressure_o2_supply\": 0, \"pressure_o2_regulated\": 0, \"pressure_buffer\": 19.465701, \"pressure_inhale\": 280.141933, \"pressure_patient\": 0, \"temperature_buffer\": -5.383, \"pressure_diff_patient\": 0, \"readback_valve_air_in\": 0, \"readback_valve_o2_in\": 0, \"readback_valve_inhale\": 0, \"readback_valve_exhale\": 0, \"readback_valve_purge\": 0, \"readback_mode\": 0}, \"alarms\": null}"
ERROR: Got invalid document
"l}"
Recieved out of order data, discarding ( previous_timestamp = 8140.08 current_timestamp = 0 )
ERROR: Got invalid document
"s\": null}"
ERROR: Got invalid document
""
ERROR: Got invalid document
"}"
ERROR: Got invalid document
"type\": \"broadcast\", \"sensors\": {\"version\": 161, \"timestamp\": 8608.439999999999, \"fsm_state\": \"IDLE\", \"pressure_air_supply\": 0, \"pressure_air_regulated\": 0, \"pressure_o2_supply\": 0, \"pressure_o2_regulated\": 0, \"pressure_buffer\": 19.251063, \"pressure_inhale\": 278.727058, \"pressure_patient\": 0, \"temperature_buffer\": -90.051, \"pressure_diff_patient\": 0, \"readback_valve_air_in\": 0, \"readback_valve_o2_in\": 0, \"readback_valve_inhale\": 0, \"readback_valve_exhale\": 0, \"readback_valve_purge\": 0, \"readback_mode\": 0}, \"a{\"type\": \"broadcast\", \"sensors\": {\"version\": 161, \"timestamp\": 8609.039999999999, \"fsm_state\": \"IDLE\", \"pressure_air_supply\": 0, \"pressure_air_regulated\": 0, \"pressure_o2_supply\": 0, \"pressure_o2_regulated\": 0, \"pressure_buffer\": 8.129176, \"pressure_inhale\": 160.001392, \"pressure_patient\": 0, \"temperature_buffer\": -332.763, \"pressure_diff_patient\": 0, \"readback_valve_air_in\": 0, \"readback_valve_o2_in\": 0, \"readback_valve_inhale\": 0, \"readback_valve_exhale\": 0, \"readback_valve_purge\": 0, \"readback_mode\": 0}, \"alarms\": null}"
ERROR: Got invalid document
"ll}{\"type\": \"broadcast\", \"sensors\": {\"version\": 161, \"timestamp\": 11902.359999999926, \"fsm_state\": \"IDLE\", \"pressure_air_supply\": 0, \"pressure_air_regulated\": 0, \"pressure_o2_supply\": 0, \"pressure_o2_regulated\": 0, \"pressure_buffer\": 3.153729, \"pressure_inhale\": 63.09325, \"pressure_patient\": 0, \"temperature_buffer\": -9.729, \"pressure_diff_patient\": 0, \"readback_valve_air_in\": 0, \"readback_valve_o2_in\": 0, \"readback_valve_inhale\": 0, \"readback_valve_exhale\": 0, \"readback_valve_purge\": 0, \"readback_mode\": 0}, \"alarms\": null}"
ERROR: Got invalid document
""
ERROR: Got invalid document
""
ERROR: Got invalid document
"\"type\": \"broadcast\", \"sensors\": {\"version\": 161, \"timestamp\": 12831.499999999905, \"fsm_state\": \"IDLE\", \"pressure_air_supply\": 0, \"pressure_air_regulated\": 0, \"pressure_o2_supply\": 0, \"pressure_o2_regulated\": 0, \"pressure_buffer\": 21.428452, \"pressure_inhale\": 282.668233, \"pressure_patient\": 0, \"temperature_buffer\": 112.939, \"pressure_diff_patient\": 0, \"readback_valve_air_in\": 0, \"readback_valve_o2_in\": 0, \"readback_valve_inhale\": 0, \"readback_valve_exhale\": 0, \"readback_valve_purge\": 0, \"readback_mode\": 0}, \"alarms\": null}{\"type\": \"broadcast\", \"sensors\": {\"version\": 161, \"timestamp\": 12834.459999999906, \"fsm_state\": \"IDLE\", \"pressure_air_supply\": 0, \"pressure_air_regulated\": 0, \"pressure_o2_supply\": 0, \"pressure_o2_regulated\": 0, \"pressure_buffer\": 21.397803, \"pressure_inhale\": 276.181408, \"pressure_patient\": 0, \"temperature_buffer\": 300.671, \"pressure_diff_patient\": 0, \"readback_valve_air_in\": 0, \"readback_valve_o2_in\": 0, \"readback_valve_inhale\": 0, \"readback_valve_exhale\": 0, \"readback_valve_purge\": 0, \"readback_mode\": 0}, \"alarms\": null}"
ERROR: Got invalid document
"l}"
ERROR: Got invalid document
""
ERROR: Got invalid document
"ype\": \"broadcast\", \"sensors\": {\"version\": 161, \"timestamp\": 14677.459999999866, \"fsm_state\": \"IDLE\", \"pressure_air_supply\": 0, \"pressure_air_regulated\": 0, \"pressure_o2_supply\": 0, \"pressure_o2_regulated\": 0, \"pressure_buffer\": 3.872246, \"pressure_inhale\": 73.5666, \"pressure_patient\": 0, \"temperature_buffer\": -138.861, \"pressure_diff_patient\": 0, \"readback_valve_air_in\": 0, \"readback_valve_o2_in\": 0, \"readback_valve_inhale\": 0, \"readback_valve_exhale\": 0, \"readback_valve_purge\": 0, \"readback_mode\": 0}, \"alarms\": null}"
ERROR: Got invalid document
"{"
ERROR: Got invalid document
""
ERROR: Got invalid document
""
ERROR: Got invalid document
"type\": \"broadcast\", \"sensors\": {\"version\": 161, \"timestamp\": 15921.459999999839, \"fsm_state\": \"IDLE\", \"pressure_air_supply\": 0, \"pressure_air_regulated\": 0, \"pressure_o2_supply\": 0, \"pressure_o2_regulated\": 0, \"pressure_buffer\": 11.618709, \"pressure_inhale\": 269.782325, \"pressure_patient\": 0, \"temperature_buffer\": -166.369, \"pressure_diff_patient\": 0, \"readback_valve_air_in\": 0, \"readback_valve_o2_in\": 0, \"readback_valve_inhale\": 0, \"readback_valve_exhale\": 0, \"readback_valve_purge\": 0, \"readback_mode\": 0}, \"alarms{\"type\": \"broadcast\", \"sensors\": {\"version\": 161, \"timestamp\": 15923.079999999838, \"fsm_state\": \"IDLE\", \"pressure_air_supply\": 0, \"pressure_air_regulated\": 0, \"pressure_o2_supply\": 0, \"pressure_o2_regulated\": 0, \"pressure_buffer\": 2.798856, \"pressure_inhale\": 58.271542, \"pressure_patient\": 0, \"temperature_buffer\": -44.024, \"pressure_diff_patient\": 0, \"readback_valve_air_in\": 0, \"readback_valve_o2_in\": 0, \"readback_valve_inhale\": 0, \"readback_valve_exhale\": 0, \"readback_valve_purge\": 0, \"readback_mode\": 0}, \"alarms\": null}"
ERROR: Got invalid document
"}"
ERROR: Got invalid document
"}{\"type\": \"broadcast\", \"sensors\": {\"version\": 161, \"timestamp\": 16927.359999999815, \"fsm_state\": \"IDLE\", \"pressure_air_supply\": 0, \"pressure_air_regulated\": 0, \"pressure_o2_supply\": 0, \"pressure_o2_regulated\": 0, \"pressure_buffer\": 18.447239, \"pressure_inhale\": 267.7071, \"pressure_patient\": 0, \"temperature_buffer\": 32.812, \"pressure_diff_patient\": 0, \"readback_valve_air_in\": 0, \"readback_valve_o2_in\": 0, \"readback_valve_inhale\": 0, \"readback_valve_exhale\": 0, \"readback_valve_purge\": 0, \"readback_mode\": 0}, \"alarms\": null}"
ERROR: Got invalid document
"{\"type\": \"broadcast\", \"sensors\": {\"version\": 161, \"timestamp\": 17077.699999999815, \"fsm_state\": \"IDLE\", \"pressure_air_supply\": 0, \"pressure_air_regulated\": 0, \"pressure_o2_supply\": 0, \"pressure_o2_regulated\": 0, \"pressure_buffer\": 6.951253, \"pressure_inhale\": 121.956042, \"pressure_patient\": 0, \"temperature_buffer\": -232.684, \"pressure_diff_patient\": 0, \"readback_valve_air_in\": 0, \"readback_valve_o2_in\": 0, \"readback_valve_inhale\": 0, \"readback_valve_exhale\": 0, \"readback_valve_purge\": 0, \"readback_mode\": 0}, \"alarms\": null}{\"type\": \"broadcast\", \"sensors\": {\"version\": 161, \"timestamp\": 17077.759999999813, \"fsm_state\": \"IDLE\", \"pressure_air_supply\": 0, \"pressure_air_regulated\": 0, \"pressure_o2_supply\": 0, \"pressure_o2_regulated\": 0, \"pressure_buffer\": 6.076277, \"pressure_inhale\": 110.001108, \"pressure_patient\": 0, \"temperature_buffer\": -206.207, \"pressure_diff_patient\": 0, \"readback_valve_air_in\": 0, \"readback_valve_o2_in\": 0, \"readback_valve_inhale\": 0, \"readback_valve_exhale\": 0, \"readback_valve_purge\": 0, \"readback_mode\": 0}, \"alarms\": null}"
ERROR: Got invalid document
""
ERROR: Got invalid document
"\"type\": \"broadcast\", \"sensors\": {\"version\": 161, \"timestamp\": 21172.219999999725, \"fsm_state\": \"IDLE\", \"pressure_air_supply\": 0, \"pressure_air_regulated\": 0, \"pressure_o2_supply\": 0, \"pressure_o2_regulated\": 0, \"pressure_buffer\": 10.924117, \"pressure_inhale\": 235.756225, \"pressure_patient\": 0, \"temperature_buffer\": -735.583, \"pressure_diff_patient\": 0, \"readback_valve_air_in\": 0, \"readback_valve_o2_in\": 0, \"readback_valve_inhale\": 0, \"readback_valve_exhale\": 0, \"readback_valve_purge\": 0, \"readback_mode\": 0}, \"alarms\": null}{\"type\": \"broadcast\", \"sensors\": {\"version\": 161, \"timestamp\": 21175.419999999725, \"fsm_state\": \"IDLE\", \"pressure_air_supply\": 0, \"pressure_air_regulated\": 0, \"pressure_o2_supply\": 0, \"pressure_o2_regulated\": 0, \"pressure_buffer\": 8.190377, \"pressure_inhale\": 162.817692, \"pressure_patient\": 0, \"temperature_buffer\": -334.893, \"pressure_diff_patient\": 0, \"readback_valve_air_in\": 0, \"readback_valve_o2_in\": 0, \"readback_valve_inhale\": 0, \"readback_valve_exhale\": 0, \"readback_valve_purge\": 0, \"readback_mode\": 0}, \"alarms\": null}"
Segmentation fault
```
The sefault happened after the sever sent `2020-04-23 03:33:11,859 - INFO - Send data for timestamp: 24164.35999999966`

**Comment by chrisburr** [comment]
Fixed in https://gitlab.com/hev-sw/hev-display/-/merge_requests/3

**Comment by chrisburr** [comment]
The good news is it doesn't only happen in the middle of the night, the bad news is I have no idea what's going on.

Running in gdb:
```bash
Thread 8 "BroadcastReceiv" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x6d2f5430 (LWP 7053)]
0x76fb9c5c in memcpy () from /usr/lib/arm-linux-gnueabihf/libarmmem-v7l.so
```
Looking at the backtrace isn't very helpful:
```bash
#0  0x76fb9c5c in memcpy () at /usr/lib/arm-linux-gnueabihf/libarmmem-v7l.so
#1  0x00000000 in  ()
```
This is the traceback of all threads:
```bash
Thread 9 (Thread 0x6caf4430 (LWP 7054)):
#0  0x7528a1a0 in futex_wait_cancelable (private=0, expected=0, futex_word=0xc3448) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
#1  0x7528a1a0 in __pthread_cond_wait_common (abstime=0x0, mutex=0x0, cond=0xc3420) at pthread_cond_wait.c:502
#2  0x7528a1a0 in __pthread_cond_wait (cond=0xc3420, mutex=0x0) at pthread_cond_wait.c:655
#3  0x7569f22c in QWaitCondition::wait(QMutex*, QDeadlineTimer) () at /opt/Qt5.12/lib/libQt5Core.so.5
#4  0x7569f384 in QWaitCondition::wait(QMutex*, unsigned long) () at /opt/Qt5.12/lib/libQt5Core.so.5
#5  0x000293f0 in DataSource::popBuffer() (this=0x7efff0c0) at /home/pi/Development/hev-display/sources/datasource.cpp:405
#6  0x000263dc in BroadcastParser::run() (this=0x7efff118) at /home/pi/Development/hev-display/sources/datasource.cpp:115
#7  0x756985e0 in  () at /opt/Qt5.12/lib/libQt5Core.so.5
#8  0x75283494 in start_thread (arg=0x6caf4430) at pthread_create.c:486
#9  0x7537e578 in  () at ../sysdeps/unix/sysv/linux/arm/clone.S:73

Thread 8 (Thread 0x6d2f5430 (LWP 7053)):
#0  0x76fb9c5c in memcpy () at /usr/lib/arm-linux-gnueabihf/libarmmem-v7l.so
#1  0x00000000 in  ()

Thread 7 (Thread 0x6dea2430 (LWP 7052)):
#0  0x7528d088 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=1, futex_word=0x73137e7c <pool_mem+1444>) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
#1  0x7528d088 in do_futex_wait (sem=sem@entry=0x73137e7c <pool_mem+1444>, abstime=0x0) at sem_waitcommon.c:115
#2  0x7528d1f4 in __new_sem_wait_slow (sem=0x73137e7c <pool_mem+1444>, abstime=0x0) at sem_waitcommon.c:282
#3  0x75129548 in eglSwapBuffers () at /opt/vc/lib/libbrcmEGL.so
#4  0x72b7c704 in  () at /opt/Qt5.12/lib/libQt5EglFSDeviceIntegration.so.5

Thread 6 (Thread 0x7002f430 (LWP 7051)):
#0  0x75373cd0 in __GI___poll (timeout=-1, nfds=1, fds=0x6f7029f0) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x75373cd0 in __GI___poll (fds=0x6f7029f0, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:26
#2  0x731c6eb4 in  () at /usr/lib/arm-linux-gnueabihf/libglib-2.0.so.0

Thread 5 (Thread 0x708fd430 (LWP 7050)):
#0  0x7528d088 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=1, futex_word=0x73178384 <cecservice_notify_available_event+24>) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
#1  0x7528d088 in do_futex_wait (sem=sem@entry=0x73178384 <cecservice_notify_available_event+24>, abstime=0x0) at sem_waitcommon.c:115
#2  0x7528d1f4 in __new_sem_wait_slow (sem=0x73178384 <cecservice_notify_available_event+24>, abstime=0x0) at sem_waitcommon.c:282
#3  0x7315e720 in cecservice_notify_func () at /opt/vc/lib/libbcm_host.so
#4  0x73121cb0 in vcos_thread_entry (arg=0x73178398 <cecservice_notify_task>) at /home/dom/projects/staging/userland/interface/vcos/pthreads/vcos_pthreads.c:144
#5  0x75283494 in start_thread (arg=0x708fd430) at pthread_create.c:486
#6  0x7537e578 in  () at ../sysdeps/unix/sysv/linux/arm/clone.S:73

Thread 4 (Thread 0x710fe430 (LWP 7049)):
#0  0x7528d088 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=1, futex_word=0x731775f4 <tvservice_notify_available_event+24>) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
#1  0x7528d088 in do_futex_wait (sem=sem@entry=0x731775f4 <tvservice_notify_available_event+24>, abstime=0x0) at sem_waitcommon.c:115
#2  0x7528d1f4 in __new_sem_wait_slow (sem=0x731775f4 <tvservice_notify_available_event+24>, abstime=0x0) at sem_waitcommon.c:282
#3  0x7315d3b0 in tvservice_notify_func () at /opt/vc/lib/libbcm_host.so
#4  0x73121cb0 in vcos_thread_entry (arg=0x73177608 <tvservice_notify_task>) at /home/dom/projects/staging/userland/interface/vcos/pthreads/vcos_pthreads.c:144
#5  0x75283494 in start_thread (arg=0x710fe430) at pthread_create.c:486
#6  0x7537e578 in  () at ../sysdeps/unix/sysv/linux/arm/clone.S:73

Thread 3 (Thread 0x718ff430 (LWP 7048)):
#0  0x7528d088 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=1, futex_word=0x73178480 <dispmanx_notify_available_event+24>) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
#1  0x7528d088 in do_futex_wait (sem=sem@entry=0x73178480 <dispmanx_notify_available_event+24>, abstime=0x0) at sem_waitcommon.c:115
#2  0x7528d1f4 in __new_sem_wait_slow (sem=0x73178480 <dispmanx_notify_available_event+24>, abstime=0x0) at sem_waitcommon.c:282
#3  0x731614d4 in dispmanx_notify_func () at /opt/vc/lib/libbcm_host.so
#4  0x73121cb0 in vcos_thread_entry (arg=0x731791c0 <dispmanx_notify_task>) at /home/dom/projects/staging/userland/interface/vcos/pthreads/vcos_pthreads.c:144
#5  0x75283494 in start_thread (arg=0x718ff430) at pthread_create.c:486
#6  0x7537e578 in  () at ../sysdeps/unix/sysv/linux/arm/clone.S:73

Thread 2 (Thread 0x72298430 (LWP 7047)):
#0  0x7537651c in ioctl () at ../sysdeps/unix/syscall-template.S:78
#1  0x7313a010 in completion_thread () at /opt/vc/lib/libvchiq_arm.so
#2  0x73121cb0 in vcos_thread_entry (arg=0x7314d318 <vchiq_instance+16>) at /home/dom/projects/staging/userland/interface/vcos/pthreads/vcos_pthreads.c:144
#3  0x75283494 in start_thread (arg=0x72298430) at pthread_create.c:486

Thread 1 (Thread 0x73025010 (LWP 7044)):
#0  0x75373cd0 in __GI___poll (timeout=12, nfds=4, fds=0x580a78) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x75373cd0 in __GI___poll (fds=0x580a78, nfds=4, timeout=12) at ../sysdeps/unix/sysv/linux/poll.c:26
#2  0x731c6eb4 in  () at /usr/lib/arm-linux-gnueabihf/libglib-2.0.so.0
(gdb)
```
I'm giving up for now
