### ISSUE TITLE
last_N_data() crash due to missing column in db.

### ISSUE THREAD

**Issue by dhcroft** [hev-sw/hev-sw#40]
For code up to commit
https://github.com/hev-sw/hev-sw/commit/7dcd41a1d5c25e07f09dca6680663ca3aa8ddb44
 (I am not blaming this commit!, just where my installation is up to)

Log fragment from app.py (including traceback below)

 The last_N_data() function in app.py fails due to the sqlite db not having "payload_type" as a column. Note this was run with : 
 python3.8 hevserver.py --inputFile share/sample.txt 
and
 python3.8 app.py

 So this might be the empty db in the repository.  I'll have a look at fixing this.

Log fragment:

Table exists.
2117
2020-05-04 11:17:32,076 - INFO - 127.0.0.1 - - [04/May/2020 11:17:32] "GET /charts HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/dhcroft/.local/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/dhcroft/.local/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/home/dhcroft/.local/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/dhcroft/.local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/dhcroft/.local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/dhcroft/.local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/dhcroft/.local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/dhcroft/.local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/dhcroft/.local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/dhcroft/.local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/dhcroft/HEV/dhcroft/hev-sw/raspberry-backend/app.py", line 45, in charts
    return render_template('charts.html', result=last_N_data())
  File "/home/dhcroft/HEV/dhcroft/hev-sw/raspberry-backend/app.py", line 175, in last_N_data
    cursor.execute(" SELECT {var} "
sqlite3.OperationalError: no such column: payload_type
2020-05-04 11:17:32,083 - INFO - 127.0.0.1 - - [04/May/2020 11:17:32] "GET /live-data?_=1588587449169 HTTP/1.1" 200 -

**Comment by dhcroft** [comment]
I think it is that the HEV_monitoringDB.sqlite has a column data_type instead of payload_type. I guess when that is replaced with a newer one the problem will be solved.

**Comment by seadanda** [comment]
Hi @dhcroft yes this is a change in the PayloadFormat, the `data_type` field has been removed from `DATA`, `READBACK` and `CYCLE` data frames, and instead there is a `payload_type` for all of those as well as the `ALARM` and `CMD` frames. Did deleting the old database fix the issue?

**Comment by dhcroft** [comment]
Deleting the old DBs does fix the crash. I am getting a problem where the data updates really slowly at the moment but that is a separate problem. The databases should be replaced with new ones when they are available.
